POST http://localhost:4000/api/v1/garden
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmYWJpYW5AZ21haWwuY29tIiwiaWF0IjoxNjg2MzI2MTcwfQ.4VHNvX35Gq1eoq98Wx7fwXCjEHUNwoyVEbDRa7stdDE


{
  "name": "cat",
  "image": "https://i.natgeofe.com/n/548467d8-c5f1-4551-9f58-6817a8d2c45e/NationalGeographic_2572187_square.jpg",
  "plant_type": "cat",
  "min_temperature": 20,
  "max_temperature": 30,
  "water_levels": 0,
  "sun_levels": 0,
  "user_id": 1,
  "device_mac": "123"
}
